### ISSUE TITLE
Auto Synch Time Control

### ISSUE THREAD

**Issue by baranidesign** [wind101net/atmo#6]
Under Setup menu...or where you see fit, add Auto Synch Time menu item that brings up a dialog (check box item) to enable auto-synchronization of DAQ time with computer upon connecting via USB.

**Comment by aarondandy** [comment]
Because the firmware does (or did) not handle ANY changes very well, I think it would be OK to implement this so it only syncs when the time difference is larger than 1.5 seconds, sound OK to you? a) I don't want to have too many options for something simple b) If you need something more frequent you can just push the button.

**Comment by baranidesign** [comment]
I Agree! :-)
